services:
  cdbapi:
    image: ${DOCKER_REGISTRY-}cdbapi
    container_name: cdbapi
    build:
      context: .
      dockerfile: CalculoCDB.API/Dockerfile
    ports:
      - "5000:80"

  # cdbapp:
  #   image: node
  #   container_name: cdbapp
  #   command: ng serve
  #   ports:
  #     - "4200:4200"
  